name: mysite
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  flutter_svg: ^2.1.0
  sizer: ^3.0.5
  connectivity_plus: ^7.0.0
  url_launcher: ^6.1.2
  carousel_slider: ^5.0.0
  animated_text_kit: ^4.2.1
  scrollable_positioned_list: ^0.3.5
#  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/icons/
    - assets/gif/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
